---
# tasks file for ansible-role-win-domain-member
- name: Get network adapter name
  win_shell: |
    $output = (Get-NetIPConfiguration |Where-Object {$_.IPv4Address.IPAddress.Length -gt 0 }|Select-Object -First 1).InterfaceAlias
    Write-Host $output -NoNewLine
  register: nic_name
  when: __dns_client_adapter is undefined

- name: set __dns_client_adapter variable
  set_fact:
    __dns_client_adapter: '{{ nic_name.stdout }}'
  when: nic_name.stdout is defined

- name: 'set dns client IP address to {{ __dns_client_dns_server_ip }}'
  win_dns_client:
    adapter_names: '{{ __dns_client_adapter }}'
    ipv4_addresses: '{{ __dns_client_dns_server_ip }}'
  when: __dns_client_configure

- name: 'join domain into ou'
  win_domain_membership:
    dns_domain_name: '{{ __dns_domain_name }}'
    hostname: '{{ __hostname }}'
    domain_admin_user: '{{ __domain_join_user }}'
    domain_admin_password: '{{ __domain_join_password }}'
    domain_ou_path: '{{ __domain_ou_path }}'
    state: domain
  register: __domain_state_ou
  when: __domain_ou_path is defined

- name: 'join domain {{ __dns_domain_name }}'
  win_domain_membership:
    dns_domain_name: '{{ __dns_domain_name }}'
    hostname: '{{ __hostname }}'
    domain_admin_user: '{{ __domain_join_user }}'
    domain_admin_password: '{{ __domain_join_password }}'
    state: domain
  register: __domain_state
  when: __domain_ou_path is undefined

- name: Reboot when domain join requires it
  win_reboot:
  when:
    - __domain_ou_path is undefined 
    - __domain_state.reboot_required

- name: Reboot when domain join (with OU) requires it
  win_reboot:
  when: 
    - __domain_ou_path is defined
    - __domain_state_ou.reboot_required
